### ISSUE TITLE
Error in version check

### ISSUE THREAD

**Issue by SanderSade** [SanderSade/dlFilter#10]
```
[17/06/05 19:07:19] [DLFilter] Checking for dlFilter updates...
-
* /sockopen: insufficient parameters (line 1918, DLFilter.mrc)
```

Also, can you fix casing of the script name to dlFilter everywhere....

**Comment by Sophist-UK** [comment]
Works for me - what version of mIRC are you running?

Can you echo the sockopen line and see what it is getting?

**Comment by SanderSade** [comment]
I got the error on mIRC 7.32 - after update to 7.49 the update check works. I am not sure if we need to worry about lower versions or not?

**Comment by Sophist-UK** [comment]
According to http://www.mirc.co.uk/versions.txt , in mIRC 7.44 $regml().group was added. This is used in my $DLF.regml extension to fix $regml using the wrong index when a group is empty. This is used in the analysis of the URL when you get the dlFilter.version file or try to download.

So, I guess the minimum version needed for this now is 7.44 which was released in March 2016. 

This is relatively recent. There will undoubtedly be people who are running on earlier versions of mIRC who don't want to, or can't upgrade to newer versions.

So, one thing we should do is to track in dlFilter.version the minimum mIRC version and not download a new version which is incompatible with the users version of mIRC.

Another thing we should do is to save the old version of dlFilter for recovery if the new version has problems rather than delete it.

Finally we should think, whether I need to rework this code to avoid the need for $regml.group and make it work on earlier versions of mIRC.

**Comment by Sophist-UK** [comment]
On reflection, I don't see a problem with requiring 7.44.

We will just have to be careful to warn people when we upgrade the version number on your dukelupus site and they come looking for the new version.

**Comment by SanderSade** [comment]
Yes, I see no major problems. v1.x will continue to work for people who cannot upgrade. 
Alternatively, we could have some kind of polyfill solution for older versions, but that is always a risky road to take. 

On minimum mIRC version in dlFilter.version - current 1.xx doesn't know how to check that, so it becomes moot for current issue. Otherwise, I am not sure we can rely being on the "bleeding edge" anyway, as people are rather slack when it comes to updating something that just works as it is...

One thing you could do, though, is to have a hardcoded minimum mIRC version in the script, and on load check if current $version is above that - and pop up message pointing them to v1.x release or ask to update - but also allow continuing with a warning "Some features may not work..."

P.S. Very nice work with the change log!

**Comment by Sophist-UK** [comment]
Minimum mirc version now in #13.
